# Generated by Django 5.0.4 on 2024-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
