# Generated by Django 5.0.4 on 2024-05-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_alter_pessoajuridica_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='quantEmpregados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
